### ISSUE TITLE
Add snowing as a weather pattern

### ISSUE THREAD

**Issue by mcavarano** [Villhellm/lovelace-animated-background#32] opened 2020-07-07 14:12 UTC
Use the snowing state of the weather sensor to trigger an animated snowing background.

**Comment by Villhellm** [comment] 2020-07-07 14:19
The cinemagraphs and states provided are just examples. Any additional states wanted/needed are up to you.
Also this is a duplicate of #27

**Closed as completed by Villhellm** 2020-07-07 14:19 UTC
