### ISSUE TITLE
Snow Option?

### ISSUE THREAD

**Issue by tlmarion** [Villhellm/lovelace-animated-background#27] opened 2020-05-08 21:26 UTC
Unfortunately I live in Northeast US and we are getting snow.. ( yea i know i don't like it either) I am not sure if i have the code right to add in another weather condition. Or what happens when weather is giving 2 weather conditions at the same time. ie snowy,rainy. Right now it goes to the default.. anyway to change that?

**Describe the solution you'd like**
Would like the option of adding additional weather conditions and to possibly accommodate the 2 conditions given by weather home.

BTW love the backgrounds! Reminds me of places I have been. 

Thanks so much in advance.

**Comment by Villhellm** [comment] 2020-05-08 21:28
What version of the plugin are you running?

**Comment by Villhellm** [comment] 2020-05-08 21:42
Once you're on the latest version here are a couple snow videos I found. Just add snow to your config with either or both of these videos.

https://cdn.flixel.com/flixel/ndza6yswd0k6vlboxyhk.hd.mp4
https://cdn.flixel.com/flixel/psi1hhbsshcus8eumtr7.hd.mp4

I don't know of any weather integrations that return more than one state, but if they do then you would have to define a state_url for whatever the state is.

**Comment by tlmarion** [comment] 2020-05-09 12:11
Great! Thank you!.. I apologize I went AFK after writing this yesterday. I am running the latest release the one you release yesterday.  And yea its weird.. I am using the weather home (built in Weather from HA) and it had Snowy, rainy as its present weather.. and I was trying to figure out great okay how do I add a comma into the YAML.  Thank you again for a wonderful plugin.

I noticed that the option to add your own was taken out of the readme is that a code issue?

**Comment by Villhellm** [comment] 2020-05-09 15:16
Entities sometimes have states that are human readable with their “true state” hidden from plain view. To see the actual state of an entity you need to go into developer tools and switch to the STATES tab. The actual state of the entity can be seen there. It’s most likely something like “snowy_rainy”, but you’ll have to check to be sure.

To what are you referring when you say “add your own “? Do you mean add your own video? You can put any mp4 video link in the state_url section. I don’t explicitly explain that, I’ll make sure to add an explanation in the state_url about what type of link it’s expecting.

**Comment by Villhellm** [comment] 2020-05-13 13:44
I'll continue to help here if you run into more issues, but I'm going to close this as it is not a bug.

**Closed as completed by Villhellm** 2020-05-13 13:44 UTC
